name: linting and testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
jobs:
  integration:
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: get repository code
        uses: actions/checkout@v4
      - name: starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install deps
        run: npm ci
      - name: run eslint
        run: npm run lint
      - name: run unit tests
        run: npm run test
